### ISSUE TITLE
Compatibility certification request for EE4J implementation of Jakarta Expression Language

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/el-ri#103]
- [x] Organization Name ("Organization") and, if applicable, URL
  Eclipse Foundation
- [x] Product Name, Version and download URL (if applicable)
  [EE4J Implementation of Expression Language 3.0.3](https://eclipse-ee4j.github.io/el-ri)
- [x] Specification Name, Version and download URL
   [Jakarta Expression Language 3.0](https://jakarta.ee/specifications/expression-language/3.0/)
- [x] TCK Version, digital SHA-256 fingerprint and download URL
  [Jakarta Expression Language TCK 3.0.0](https://download.eclipse.org/jakartaee/expression-language/3.0/jakarta-expression-language-tck-3.0.0.zip), SHA-256: 7af99b28c81c1f7eba1e241b20f3854289ae511c8446158671f32731c785504c
- [x] Public URL of TCK Results Summary
  [TCK results summary](https://eclipse-ee4j.github.io/el-ri/certifications/expression-language/3.0/TCK-Results)
- [x] Any Additional Specification Certification Requirements
  None
- [x] Java runtime used to run the implementation
  Oracle JDK 1.8.0_202
- [x] Summary of the information for the certification environment, operating system, cloud, ...
  Linux
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by edbratt** [comment]
Looks good to me. Accept and close?

**Comment by m0mus** [comment]
Accepted by Lazy Consensus.
