### ISSUE TITLE
Deliver el-ri Specification Version update for Jakarta EE 9

### ISSUE THREAD

**Issue by kwsutter** [eclipse-ee4j/el-ri#116]
**Is your feature request related to a problem? Please describe.**
Jakarta EE 9 is the next major release, with the main focus of moving from the ```javax``` namespace to the ```jakarta``` namespace.

**Describe the solution you'd like**
This issue will be used to track the progress of this work effort via the [Jakarta EE 9 Project board](https://github.com/orgs/eclipse-ee4j/projects/17).

**Additional context**
[Jakarta EE Specification Process](https://jakarta.ee/about/jesp/)
[Eclipse Project Handbook](https://www.eclipse.org/projects/handbook/#release)
[Eclipse Release Record for Jakarta EE 9](https://projects.eclipse.org/projects/ee4j.jakartaee-platform/releases/9)

**ToDo**
- [x] **[Create Eclipse Release Record](https://www.eclipse.org/projects/handbook/#pmi-commands-release) in your respective Jakarta Specification Project.**
 Most Component Release Records will just reference the [Jakarta EE 9 Platform Release Plan](https://eclipse-ee4j.github.io/jakartaee-platform/jakartaee9/JakartaEE9ReleasePlan).  But, if your Component deviates at all from the Platform Release Plan, then a description of the changes will be required in the Release Record.
- [x] **Initiate a ballot for your Jakarta Release Record/Plan.**
 Again, if your component is only doing the required minimum as defined by the [Jakarta EE 9 Platform Release Plan](https://eclipse-ee4j.github.io/jakartaee-platform/jakartaee9/JakartaEE9ReleasePlan), then no separate ballot is required.  You are already approved.  But, if your component deviates from the Platform Release Plan, then you will need to initiate your own ballot as defined by the [Jakarta EE Specification Process](https://jakarta.ee/about/jesp/).
- [x] **Jakarta-ize your Specification document (if applicable)**
 Many of the Jakarta EE components now have the source for their Specification documents.  It is strongly recommended that these Specification documents are properly updated to represent Jakarta EE instead of Java EE.  Some [helpful instructions are documented](https://github.com/jakartaee/specification-committee/blob/master/steps_javaee_to_jakartaee.adoc) here.
- [x] **javax -> jakarta Spec updates**
 If your component has Specification source, then all javax package references need to be updated to use jakarta package references.
- [x] **javax -> jakarta API updates**
 Your component APIs need to move from using the javax namespace to using the jakarta namespace.
- [x] **Release Candidate (RC) of Jakarta API in Maven Central**
 A Release Candidate of your component API should be pushed to Maven Central as soon as humanly possible.  This will allow other dependent components to utilize your APIs as they are updating their APIs.  Multiple revisions of these Release Candidate APIs are allowed (and probably expected) during the development cycle.
- [x] **javax -> jakarta TCK updates**
 Your component TCK needs to be updated to use the jakarta namespace.
- [x] **javax -> jakarta Compatible Implementation updates**
 Your compatible implementation that will be used to demonstrate completeness of the Specification needs to be updated to use the jakarta namespace.
- [x] **Final Jakarta API available in Staging Repo**
 When ready, your final version of the API needs to be staged to get ready for the PR review and approvals.
- [x] **Draft Specification and Apidoc PRs ready for review**
 Like we did for Jakarta EE 8, draft PRs need to be created and reviewed in preparation for the final ballots.
- [x] **Release Review Ballot started**
 Each Jakarta EE component will need to initiate a separate Release Review ballot after proper reviewing has completed.  To be clear, there will not be a blanket Release Review for all of Jakarta EE 9 like we did for the Plan Review.  Each component needs a separate Release Review.

**Comment by kwsutter** [comment]
Now that you have an RC for the API, can I ask that you post a link to the Maven artifact on the project board?  https://github.com/orgs/eclipse-ee4j/projects/17#column-7346435

Thanks!

**Comment by pnicolucci** [comment]
Jakarta Expression Language 4.0.0 Release Plan: https://projects.eclipse.org/projects/ee4j.el/releases/4.0.0

**Comment by pnicolucci** [comment]
Once an RC is released I'll update the project board with a link to it.

**Comment by arjantijms** [comment]
Jakartified implementation: https://github.com/eclipse-ee4j/el-ri/commit/d09916a4c2341f743bac80b842959d7d44f1c181#diff-86ccec3d9ff0e9c0514506e982cdc08b

**Comment by arjantijms** [comment]
Jakartified TCK: https://github.com/eclipse-ee4j/jakartaee-tck/commit/b612698516e77768a46606dd6f61a35c9e754f0a

**Comment by kwsutter** [comment]
One last request for the Specifications PR to promote the Milestone deliverables for this Project.  The PR is created against the [Jakarta EE specifications github repo](https://github.com/jakartaee/specifications/pulls).  A template is automatically used when creating PRs against this repo which should help with understanding the steps required for a successful merge.  We're not looking for perfection for this Milestone.  We just want the ability to promote the great work that all of the Projects are doing.

If you submit a PR, please feel free to move this Epic to the [Milestone 1 Ready column in the Project Board](https://github.com/orgs/eclipse-ee4j/projects/17#column-9442495).  Thanks!

**Comment by markt-asf** [comment]
It is on the way. I've been struggling POMs, the CI system, trying to figure out the original intention of the authors and Maven best practices. I think I'm there now. Should be able to get to this later today.

**Comment by markt-asf** [comment]
PRs submitted. Minor changes might be required. That can be tracked on those PRs,
https://github.com/jakartaee/specifications/pull/206
https://github.com/jakartaee/specifications/pull/207

**Comment by kwsutter** [comment]
@markt-asf, can we please re-open this Issue?  This is the overall Epic issue for delivering the complete EL Specification version for Jakarta EE 9.  We're not quite there yet...  Thanks!

**Comment by markt-asf** [comment]
Sure. Done.

**Comment by kwsutter** [comment]
Looking for an update on the status of the Expression Language Final Specification PR.  If we're going to make the [Sept deliverable goal](https://eclipse-ee4j.github.io/jakartaee-platform/jakartaee9/JakartaEE9#jakarta-ee-9-schedule), then this Wave 1 Specification needs to be ready for final ballot by Monday, July 19.  Which means that the Specification PRs should already be created and under a "mentorship" review.  Can I ask what the plans are for this Specification?  Thanks!

**Comment by markt-asf** [comment]
I was about to say EL is ready to go and I'll get on with starting the final release then I saw #130. We need info from Glassfish as to what the issue is before we can proceed.

**Comment by arjantijms** [comment]
Spec PR: https://github.com/jakartaee/specifications/pull/225
Javadoc PR: https://github.com/jakartaee/specifications/pull/226

**Comment by arjantijms** [comment]
Ballot: https://www.eclipse.org/lists/jakarta.ee-spec/msg00895.html

**Comment by arjantijms** [comment]
CQ: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=22589

**Comment by arjantijms** [comment]
- [X] Review concluded: https://bugs.eclipse.org/bugs/show_bug.cgi?id=567011#c6
