### ISSUE TITLE
Add missing generics to API

### ISSUE THREAD

**Issue by markt-asf** [eclipse-ee4j/el-ri#119]
There are a handful of methods  (`putContext()` and `getContext()` in `ELContext` and `StandardELContext`) that use `Class` rather than `Class<?>` for a method parameter.

Ignoring the `javax` to `jakarta` change (since I'm expecting tools to automate that) this addition of these generics is a binary compatible one so it will not cause breakage for existing applications using this API.

We will need to update the signature files in the TCK to account for this change.

**Comment by arjantijms** [comment]
+1 from me. This is so long overdue it's not funny anymore. Since we have to update the signature files anyway, now would be as good a time as any.
