### ISSUE TITLE
Jakarta EL 3 example in standalone application

### ISSUE THREAD

**Issue by PashaTurok** [eclipse-ee4j/el-ri#139]
Could anyone provide an example how to use Jakarta EL 3 in a standalone application (without any containers). For example, if I have `${100 + 200}` how to execute this expression?

**Comment by markt-asf** [comment]
https://jakarta.ee/specifications/expression-language/3.0/apidocs/javax/el/ELProcessor.html

**Comment by PashaTurok** [comment]
@markt-asf Thank you very much. It can be funny, but all examples I found in internet were about implementing context, resolver and mappers although Processor is enough for me.
