### ISSUE TITLE
Complete Release of Expression Language 4.0

### ISSUE THREAD

**Issue by MattGill98** [eclipse-ee4j/el-ri#143]
These are the remaining steps as per the spec-committee guide for the project team to complete to finalise the release of [Expression Language 4.0](https://github.com/jakartaee/specifications/pull/225):

 - [x] promotes api staging release promotes the specification api jars to maven central. An example release job script can be found here https://wiki.eclipse.org/MavenReleaseScript.
 - [x] go through the merged jakarta.ee specification website page to verify all the links are valid.
 - [x] approve the compatibility request.
 - [x] The compatible implementation project/vendor MUST send an email to tck@eclipse.org for approval of the compatible implementation for trademark usage.
 - [x] merge any final release branch as appropriate for the branch management for the project.

**Comment by arjantijms** [comment]
Everything has been done, so this can be closed. Thanks @MattGill98 for the help!
