### ISSUE TITLE
jakarta.el artifact does not contain APIs

### ISSUE THREAD

**Issue by lukasj** [eclipse-ee4j/el-ri#145]
In pre-4 versions, `org.glassfish:jakarta.el` used to be an API + implementation bundle, as of (current) version 4.0.0 in staging this is not the case, thus can be seen as a regression, since other projects like activation, mail or jsonp are still following the original pattern.

It wouldn't be bad to at least document this change somewhere if return to original "design" is not intended.

**Comment by arjantijms** [comment]
Indeed, is was an explicit choice by the team to provide the separate versions from now on. GlassFish was updated to this new reality.

The second anticipated step is to have the API and implementation in separate repos, and have separate Eclipse projects backing these, just like e.g. Jakarta Security, Authentication, Authorization, Rest, Enterprise Beans, Servlet, etc has.

It would be good to document this somewhere. @markt-asf any idea for the best location? Maybe the readme in this repo?

**Comment by lukasj** [comment]
...or in some to "to Jakarta" migration guide...

**Comment by markt-asf** [comment]
Adding an explanation of the current repo structure to the readme seems reasonable and it can then be updated as and when the repos are split.
