### ISSUE TITLE
Build CI/CD pipeline

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/el-ri#49]
This task is for creating a basic build CI/CD pipeline for this project on Eclipse infrastructure. More information is here: https://ci.eclipse.org/.

**Comment by arjantijms** [comment]
Project CI environment has been requested:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=538672

**Comment by m0mus** [comment]
Update from @arjantijms:
```
Warnings/errors fixed in master branch. Still has to be merged to EE4J_8.
Two jobs created. 
Simple maven job for master builds - succeeds
Release job based on shell script and using secret files; only initial setup
```
Closing this task as completed based on the status above.
