### ISSUE TITLE
Release pipeline and first release

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/el-ri#50]
We need to create a release CI/CD pipeline for this project and release the first version from Eclipse. 

Use these documents as a reference:

- [How to release the first Eclipse version of projects](https://github.com/eclipse-ee4j/ee4j/wiki/How-to-release-the-first-Eclipse-version-of-projects)
- [JSONP release job](https://github.com/eclipse-ee4j/jsonp/wiki/JSONP-release-job)

**Comment by m0mus** [comment]
Update from @arjantijms:
```
Release job based on shell script and using secret files; only initial setup
```

**Comment by vinayvishal** [comment]
> This job is in final leg. Getting gpg related error, once fixed, this task can be marked done.
> 
> ```shell
> gpg: signing failed: Not a tty
> gpg: signing failed: Not a tty
> ```

This issue is fixed. With this we have a working release job for el-ri/api.

**Comment by vinayvishal** [comment]
Note that no actual release has been done yet. DRY_RUN succeeds.
