### ISSUE TITLE
Release API to OSSRH staging repository

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/el-ri#57]
- [ ] Uptake new Eclipse versions of dependencies (if any). Use [GlassFish 5.1 Release Tracker](https://wiki.eclipse.org/Eclipse_GlassFish_5.1_Components_Release_Tracker) wiki to find components versions to use.

- [ ] Release to OSSRH staging repository

- [ ] Update [GlassFish 5.1 Release Tracker](https://wiki.eclipse.org/Eclipse_GlassFish_5.1_Components_Release_Tracker) with released version number.

**Comment by markt-asf** [comment]
The EE4J_8 branch is good to go as is the release build on Jenkins. I believe (correct me if I am wrong) we need to wait for the JakartaEE EL 3.0 release and then update our dependencies before we release the JSP API.

**Comment by markt-asf** [comment]
The EE4J_8 branch is almost good to go as is the release build on Jenkins. We just need to update the license headers in master (#60 is waiting for an approval) and the apply the same change to the EE4J_8 branch.
There are also some 'nice to have' clean-ups that we may or may not get to, time permitting.

**Comment by markt-asf** [comment]
The EE4J_8 branch is now good to go for the release build in Jenkins. I've just run the release build manually (build 25) and all looks good.

**Comment by markt-asf** [comment]
And I have now figured out how to get it to show up at:
https://oss.sonatype.org/content/groups/staging/jakarta/el/jakarta.el-api/

**Comment by vinayvishal** [comment]
@markt-asf @m0mus , https://github.com/eclipse-ee4j/el-ri consists of both api and ri. Was there an ri release to staging too? As part of https://github.com/eclipse-ee4j/el-ri/issues/72, do we need to just integrate the api or ri as well. I don't basically see an ri release done for this.

**Comment by markt-asf** [comment]
That is news to me. I signed up to work on the API and the spec, not the implementation. I have no idea what state the RI code is in.

**Comment by arjantijms** [comment]
@vinayvishal 

The EL project is one of those "special" projects. It contains a combined API + RI, and then hacks the API off of it. It's done in a pretty nasty way, but seemingly does work to some degree.

The coordinates of the combined jar are:

```xml
    <groupId>org.glassfish</groupId>
    <artifactId>jakarta.el</artifactId>
    <version>3.0.2</version>
```

**Comment by arjantijms** [comment]
@senivam

That should not be correct.

The coordinates as announced in the release mail were org.glassfish:jakarta.el.

See: https://www.eclipse.org/lists/el-dev/msg00016.html

**Comment by arjantijms** [comment]
@senivam Additionally, the com.sun.el:el-ri coordinates were last used in 2008, and thereafter never since. See https://mvnrepository.com/artifact/com.sun.el/el-ri

**Comment by arjantijms** [comment]
@m0mus @senivam 

After fixing the release script and re-running the script, it's now finally staged:

See: https://oss.sonatype.org/content/repositories/staging/org/glassfish/jakarta.el/3.0.2/

This is the artefact that corresponds to the recently released `org.glassfish:javax.el` See: https://mvnrepository.com/artifact/org.glassfish/javax.el

**Comment by ricogu** [comment]
Hi, team. Will this artifect available in Maven central soon?
