### ISSUE TITLE
Update Scope Statement for Jakarta Expression Language Project

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/el-ri#83]
Update the scope statement for the project: https://projects.eclipse.org/projects/ee4j.jakartaee-platform/governance

See https://docs.google.com/spreadsheets/d/1FPLjo_DJDOQngVtdrYgaDk98d9NBG-0ODgdmOG3LOsI/edit?usp=sharing for examples.

**Comment by markt-asf** [comment]
This is the current scope statement:

> Eclipse Expression Language provides the API, reference implementation and TCK for Java Expression Language, starting from the specification defined by JSR-341.

Using WebSocket as an example, I suggest:

> Jakarta Expression Language provides a specification document, API, reference implementation and TCK that describes an expression language for Java(R) applications.

**Comment by smillidge** [comment]
@markt-asf  once you are happy with the scope can you move to the "Ready for Review" column in the project?

**Comment by markt-asf** [comment]
I'm ahppy with the scope but unclear what action is required. Can you be a little more specific please?

**Comment by smillidge** [comment]
If you can move your issue to the "Ready for Review..." column in the project https://github.com/orgs/eclipse-ee4j/projects/10 this indicates that it can go to spec committee for review.

**Comment by markt-asf** [comment]
Got it. Tx. Done.

**Comment by waynebeaton** [comment]
The scope of the specification itself is:

> Jakarta Expression Language defines an expression language for Java applications.

Is this enough? Is the context constrained? Is it, for example, specific to JSP?

Note that the (R) is not required.

**Comment by markt-asf** [comment]
No, the context is not constrained. The (R) was there because it was in the original I based the text on. Happy to see it go.
