### ISSUE TITLE
Change project name to Jakarta Expression Language

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/el-ri#84]
Background information:
https://waynebeaton.wordpress.com/2019/04/04/renaming-java-ee-specifications-for-jakarta-ee/

Checklist:
- [x]  GitHub
- [x]  README file
- [x]  CONTRIBUTING file
- [x]  Eclipse Project under https://projects.eclipse.org/projects/ee4j

**Comment by ivargrimstad** [comment]
Any objections to Jakarta Expression Language?

**Comment by arjantijms** [comment]
No objection from my side. Sounds perfectly reasonable.

**Comment by markt-asf** [comment]
+1
